export const MOCK_DATA = [
  {
    id: 1,
    nickname: '유재석',
    profileImage: 'https://via.placeholder.com/150',
    summary: '유쾌함과 전문성을 갖춘 15년 경력의 이사 전문가입니다.',
    reviewStats: { averageScore: 4.9, totalReviews: 80 },
    price: 140000,
    serviceRegion: ['서울', '경기'],
    serviceType: ['가정이사'],
    isAssigned: false,
    career: 15,
    confirmationCount: 55,
    favoriteCount: 200,
    isLiked: true,
  },
  {
    id: 2,
    nickname: '강호동',
    profileImage: 'https://via.placeholder.com/150',
    summary: '강력한 체력과 노련함으로 20년간 사무실 이사를 책임졌습니다.',
    reviewStats: { averageScore: 4.7, totalReviews: 60 },
    price: 180000,
    serviceRegion: ['부산', '울산'],
    serviceType: ['사무실이사'],
    isAssigned: false,
    career: 20,
    confirmationCount: 90,
    favoriteCount: 150,
    isLiked: false,
  },
  {
    id: 3,
    nickname: '손예진',
    profileImage: 'https://via.placeholder.com/150',
    summary: '세심함이 강점인 12년 경력의 소형 이사 전문가입니다.',
    reviewStats: { averageScore: 4.8, totalReviews: 50 },
    price: 130000,
    serviceRegion: ['인천', '서울'],
    serviceType: ['소형이사'],
    isAssigned: true,
    career: 12,
    confirmationCount: 30,
    favoriteCount: 250,
    isLiked: true,
  },
  {
    id: 4,
    nickname: '현빈',
    profileImage: 'https://via.placeholder.com/150',
    summary: '8년 경력으로 전국 어디든 빠르고 안전하게 이사합니다.',
    reviewStats: { averageScore: 4.5, totalReviews: 40 },
    price: 100000,
    serviceRegion: ['전국'],
    serviceType: ['가정이사', '소형이사'],
    isAssigned: false,
    career: 8,
    confirmationCount: 15,
    favoriteCount: 120,
    isLiked: false,
  },
  {
    id: 5,
    nickname: '차은우',
    profileImage: 'https://via.placeholder.com/150',
    summary: '고객 만족을 최우선으로 하는 5년 경력의 이사 전문가입니다.',
    reviewStats: { averageScore: 4.6, totalReviews: 30 },
    price: 110000,
    serviceRegion: ['대구', '경북'],
    serviceType: ['가정이사'],
    isAssigned: true,
    career: 5,
    confirmationCount: 75,
    favoriteCount: 300,
    isLiked: true,
  },
];
