export const MOCK_DATA = [
  {
    id: 1,
    nickname: '유재석',
    profileImage: 'https://via.placeholder.com/150',
    summary: '유쾌함과 전문성을 갖춘 15년 경력의 이사 전문가입니다.',
    reviewStats: { averageScore: 4.9, totalReviews: 80 },
    price: 140000,
    serviceRegion: ['SEOUL', 'GYEONGGI'],
    serviceType: ['HOUSE'],
    isAssigned: false,
    career: 15,
    confirmationCount: 55,
    favoriteCount: 200,
    isLiked: true,
    description:
      '안녕하세요. 이사업계에서 15년 동안의 경력을 가진 유재석입니다. 고객님의 소중한 물품을 안전하고 신속하게 운송해 드립니다. 가정 이사를 전문으로 하며 서울 및 경기 지역에서 서비스를 제공합니다.',
  },
  {
    id: 2,
    nickname: '강호동',
    profileImage: 'https://via.placeholder.com/150',
    summary: '강력한 체력과 노련함으로 20년간 사무실 이사를 책임졌습니다.',
    reviewStats: { averageScore: 4.7, totalReviews: 60 },
    price: 180000,
    serviceRegion: ['BUSAN', 'ULSAN'],
    serviceType: ['OFFICE'],
    isAssigned: false,
    career: 20,
    confirmationCount: 90,
    favoriteCount: 150,
    isLiked: false,
    description:
      '안녕하세요. 사무실 이사를 전문으로 20년의 경험을 쌓은 강호동입니다. 체력과 노련함으로 대규모 사무실 이사도 신속히 처리하며 부산 및 울산 지역에서 활동하고 있습니다.',
  },
  {
    id: 3,
    nickname: '손예진',
    profileImage: 'https://via.placeholder.com/150',
    summary: '세심함이 강점인 12년 경력의 소형 이사 전문가입니다.',
    reviewStats: { averageScore: 4.8, totalReviews: 50 },
    price: 130000,
    serviceRegion: ['INCHEON', 'SEOUL'],
    serviceType: ['SMALL'],
    isAssigned: true,
    career: 12,
    confirmationCount: 30,
    favoriteCount: 250,
    isLiked: true,
    description:
      '안녕하세요. 세심한 서비스로 인정받는 12년 경력의 손예진입니다. 소형 이사를 주로 다루며 인천과 서울 지역을 중심으로 고객님의 이사를 돕고 있습니다.',
  },
  {
    id: 4,
    nickname: '현빈',
    profileImage: 'https://via.placeholder.com/150',
    summary: '8년 경력으로 전국 어디든 빠르고 안전하게 이사합니다.',
    reviewStats: { averageScore: 4.5, totalReviews: 40 },
    price: 100000,
    serviceRegion: ['SEOUL', 'BUSAN'],
    serviceType: ['HOUSE', 'SMALL', 'OFFICE'],
    isAssigned: false,
    career: 8,
    confirmationCount: 15,
    favoriteCount: 120,
    isLiked: false,
    description:
      '안녕하세요. 이사 경력 8년의 현빈입니다. 전국 어디든지 안전하고 신속한 이사 서비스를 제공합니다. 가정 이사와 소형 이사 모두 가능하며 만족스러운 서비스를 약속드립니다.',
  },
  {
    id: 5,
    nickname: '차은우',
    profileImage: 'https://via.placeholder.com/150',
    summary: '고객 만족을 최우선으로 하는 5년 경력의 이사 전문가입니다.',
    reviewStats: { averageScore: 4.6, totalReviews: 30 },
    price: 110000,
    serviceRegion: ['DAEGU', 'GYEONGBUK'],
    serviceType: ['HOUSE'],
    isAssigned: true,
    career: 5,
    confirmationCount: 75,
    favoriteCount: 300,
    isLiked: true,
    description:
      '안녕하세요. 고객 만족을 최우선으로 생각하는 5년 경력의 차은우입니다. 대구와 경북 지역에서 가정 이사를 전문으로 도와드리며, 정성을 다해 이사 서비스를 제공합니다.',
  },
];
